home/urls.py
from django.conf.urls import url
from .landingpage import index
from .landingpage import returnRegister
from .landingpage import register
from .custom_auth import auth_login, auth_logout
from .profile import profile
from .form_berita import newArticle, createNewArticle, createNewPoll
from .form_berita import home

#url for app, add your URL Configuration

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
    url(r'^register/$', returnRegister, name='returnRegister'),
    url(r'^custom_auth/register/$', register, name='register'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^new-article/$', newArticle, name='new-article'),
    url(r'^create-new-article/$', createNewArticle, name='create-new-article'),
    url(r'^crete-new-poll/$', createNewPoll, name='create-new-poll'),
    url(r'^form/$', home, name='form'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import home.urls as home
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(home,namespace='home')),
    url(r'^$', RedirectView.as_view(url='home/', permanent = True), name= 'index'),
]

home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Berita(models.Model):
    url = models.CharField(primary_key=True, max_length=50)
    judul = models.CharField(max_length=100)
    topik = models.CharField(max_length=100)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    jumlah_kata = models.IntegerField()
    rerata_rating = models.FloatField()
    id_universitas = models.ForeignKey('Universitas', models.DO_NOTHING, db_column='id_universitas')

    class Meta:
        managed = False
        db_table = 'berita'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Dosen(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    nik_dosen = models.CharField(max_length=20)
    jurusan = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'dosen'


class Honor(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    tgl_diberikan = models.DateTimeField()
    jumlah_berita = models.IntegerField()
    jumlah_gaji = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'honor'
        unique_together = (('id_narasumber', 'tgl_diberikan'),)


class Komentar(models.Model):
    id = models.IntegerField(primary_key=True)
    tanggal = models.DateTimeField()
    jam = models.TimeField()
    konten = models.CharField(max_length=100)
    nama_user = models.CharField(max_length=50)
    email_user = models.CharField(max_length=50)
    url_user = models.CharField(max_length=50)
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita')

    class Meta:
        managed = False
        db_table = 'komentar'


class Kupon(models.Model):
    id = models.IntegerField(primary_key=True)
    tgl_diberikan = models.DateTimeField()
    tgl_kadaluarsa = models.DateTimeField()
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber')

    class Meta:
        managed = False
        db_table = 'kupon'


class Mahasiswa(models.Model):
    id_narasumber = models.ForeignKey('Narasumber', models.DO_NOTHING, db_column='id_narasumber', primary_key=True)
    npm = models.CharField(max_length=20)
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'mahasiswa'


class Narasumber(models.Model):
    id = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    tempat = models.CharField(max_length=30)
    no_hp = models.CharField(max_length=30)
    jumlah_berita = models.IntegerField()
    rerata_kata = models.IntegerField()
    id_universitas = models.ForeignKey('Universitas', models.DO_NOTHING, db_column='id_universitas')
    username = models.CharField(max_length=30, blank=True, null=True)
    password = models.CharField(max_length=30, blank=True, null=True)
    tanggal = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'narasumber'


class NarasumberBerita(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber')

    class Meta:
        managed = False
        db_table = 'narasumber_berita'
        unique_together = (('url_berita', 'id_narasumber'),)


class Polling(models.Model):
    id = models.IntegerField(primary_key=True)
    polling_start = models.DateTimeField()
    polling_end = models.DateTimeField()
    total_responden = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'polling'


class PollingBerita(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita')

    class Meta:
        managed = False
        db_table = 'polling_berita'


class PollingBiasa(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    url = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'polling_biasa'


class Rating(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    ip_address = models.CharField(max_length=50)
    nilai = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'rating'
        unique_together = (('url_berita', 'ip_address'),)


class Rekening(models.Model):
    nomor = models.CharField(primary_key=True, max_length=20)
    nama_bank = models.CharField(max_length=20)
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber')

    class Meta:
        managed = False
        db_table = 'rekening'


class Respon(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    jawaban = models.CharField(max_length=50)
    jumlah_dipilih = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'respon'
        unique_together = (('id_polling', 'jawaban'),)


class Responden(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'responden'
        unique_together = (('id_polling', 'ip_address'),)


class Riwayat(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    id_riwayat = models.IntegerField()
    waktu_revisi = models.DateTimeField()
    konten = models.TextField()

    class Meta:
        managed = False
        db_table = 'riwayat'
        unique_together = (('url_berita', 'id_riwayat'),)


class Staf(models.Model):
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber', primary_key=True)

home/templates/landingpage.html
<!DOCTYPE html>
<html>
<head>
<title>BMNC</title>
<link rel="icon" href="asset/bmnc.png" type="image/gif" sizes="32x32">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
<style>
	* {box-sizing: border-box;}
html{
	height: 100%;
	width: 100%;
}

body { 
	margin: 0;
	font-family: 'Comfortaa', cursive;
	/*font-family: 'Varela Round', sans-serif;*/
	background: linear-gradient(to bottom right, #33cccc -2%, #ffc1b8 105%);
	min-height: 100%;
	background-attachment: fixed;
}


.header {
  overflow: hidden;
  background-color: white; 
  padding: 10px 5px;
  -webkit-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  -moz-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
}

.logo{
	margin-left: 20px;
	height: 40px;
}
.img{
	width: 110px;
	height: 40px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  .header-right {
    float: none;
  }
}

.body-right{
	width: 40%;
	float: right;
}
.body-left{
	width: 60%;
	float: left;
	margin-bottom: 40px;
}

.form{
	display: flex;
	flex-direction: column;
	flex-wrap: wrap;
	align-content: center;
}

:focus{outline: none;}

.content-title{
	margin: 40px auto;
	margin-top: 0px;
	width: 80%;
	border-bottom: 1px solid #3333;
}
.content-titles{
	margin: 10px auto;
	margin-top: 0px;
	width: 80%;
	border-bottom: 1px solid #3333;

}

.content-title, .content-titles h1{
	font-weight: bold;
	color: #06516B;

}

.col-3{
	width: 40%; 
	margin: 10px 30%; 
	justify-content: center;
	position: relative;
	} /* necessary to give position: relative to parent. */

input[type="text"]{
	font-family: 'Comfortaa', cursive; 
	margin:auto;
	color: #333; 
	width: 150px; 
	box-sizing: border-box; 
	letter-spacing: 1px;
}

input[type="submit"]{
	font-family: 'Comfortaa', cursive; 
}

input::-webkit-input-placeholder {
    font-size: 15px;
    line-height: 3;
    letter-spacing: 1px;
}


.effect-2{
	border: 0; 
	padding: 7px 0; 
	border-bottom: 1px solid #ccc;
	margin:auto;
	width: 150px;
}

.effect-2 ~ .focus-border{
	position: absolute; 
	bottom: 0; 
	left: 50%; 
	width: 0; 
	height: 2px; 
	background-color: #3399FF; 
	transition: 0.4s;
}
.effect-2:focus ~ .focus-border{
	width: 150px; 
	transition: 0.4s; 
	left: 0;
}

::-webkit-input-placeholder {
   text-align: center;

}

:-moz-placeholder {
   text-align: center;

}

.buttons{
	align-items: center;
	align-content: center;
	align-self: center;
	margin-top: 60px;
}

.buttons p{
	margin-top: 30px;
	text-align: center;
}

.button {
  background: #FFC1B8;
  border-radius: 100px;
  width: 150px;
  height: 40px;
  padding: 10px 20px;
  color: #06516B;
  text-decoration: none;
  font-size: 18px;
  

  margin-bottom: -10px;
  margin-left: 120px;
  text-align: center;
  -webkit-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  -moz-box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
  box-shadow: 0 3px 5px rgba(57, 63, 72, 0.3);
}


.button:hover{
	cursor: pointer;
	opacity: 0.75;
}

.p{
	border-bottom: 1px solid black;
	width: 25%;
	margin:auto;
}
.p:hover{
	cursor: pointer;
	color: grey;
}

.container {
    width: 400px;
    height: 500px;
    background: white;
    float: right;
    margin-top: 130px;
    margin-right: 50px;
    bottom: 0;
    right: 100px;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
  }

.content-container {
	width: 95%;
	height: 100%;
	position: relative;
	margin: auto;
	display: flex;
	flex-direction: column;
	justify-content: center;
}

.content-def{
	width: 80%;
	align-self: center;
	text-align: justify;
	color: #666;
}

.containers {
    width: 760px;
    height: 400px;
    background: white;
    float: right;
    margin-top: 50px;
    margin-right: 50px;
    bottom: 0;
    right: 100px;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
}
.containers1 {
    width: 760px;
    height: 300px;
    background: white;
    float: right;
    margin-top: 50px;
    margin-right: 50px;
    bottom: 0;
    right: 100px;
    border-radius: 40px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.3);
  }

label {
	color: #E74C3C;
	text-transform: uppercase;
}

</style>
</head>
<body>
<div class="header">
	<div href="#default" class="logo">
		{% load static %}
		<img src="{% static "image/logo.png" %}" class="img">
	</div>
  	<div class="header-right">
    </div>
</div>

<div class="body">
	<div class="body-right">
		<div class="container">
	  		<div class="content-container">
	  			<div class="content-title">
	  				<h1>User Login</h1>
	  			</div>
	  			<form action="{% url 'home:auth_login' %}" method="POST">
	  				{% csrf_token %}
		    		<div class="form">
		    			<div class="col-3">
	        				<input for = "username" class="effect-2" type="text" name="username" placeholder="Username" required>
	            				<span class="focus-border"></span>
	        			</div>
	        			<div class="col-3">
	        				<input for = "password" class="effect-2" type="Password" name="password" placeholder="Password" required>
	            				<span class="focus-border"></span>
	        			</div>
		    		</div>
		    		<div class="buttons">
		    			<input type="submit" class="button" value="Login"></input>
		    			<p> or </p>
		    			<p class="p"> Register</p>
		    		</div>
		    	</form>
  			</div>
		</div>
	</div>
	<div class="body-left">
		<div class="containers">
	  		<div class="content-container">
	  			<div class="content-titles">
	  				<h1> What is BMNC?</h1>
	  			</div>
	  			<div class="content-def">
	  				<p><b>BMNC is a project of Database Implementation by Athifah, Kirana, and Zulia</b></p>
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	  				Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. 
	  				</p>
	  			</div>
	  		
  			</div>
		</div>
		<div class="containers1">
	  		<div class="content-container">
	  			<div class="content-titles">
	  				<h1> Why use BMNC?</h1>
	  			</div>
	  			<div class="content-def">
	  				<p><b>BMNC is a project of Database Implementation by Athifah, Kirana, and Zulia</b></p>
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	  				</p>
	  			</div>
	  		
  			</div>
		</div>
	</div>
</div>
</body>
</html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"> </script>
<script>
	$(document).ready(function(){
		var status = ({{status.status}});
		if (!status){
			alert('Username dan password salah!');
			status = false;
		}else{
			status = true;
		}
	}); 
	$('.p').click(function(){
		window.location.href = 'register';
		console.log('sampai ga');
	});

</script>